WGBH-MLA/ams

- Gemfile
- Gemfile.lock
> Pins simple_form to 3.5.0

- app/actors/hyrax/actors/work_actor.rb
- app/controllers/hyrax/works_controller.rb
- app/forms/hyrax/work_form.rb
- app/indexers/work_indexer.rb
- app/models/work.rb
- app/presenters/hyrax/work_presenter.rb
- app/views/hyrax/works/_work.html.erb
- config/initializers/hyrax.rb
- config/locales/work.de.yml
- config/locales/work.en.yml
- config/locales/work.es.yml
- config/locales/work.fr.yml
- config/locales/work.it.yml
- config/locales/work.pt-BR.yml
- config/locales/work.zh.yml
- spec/actors/hyrax/actors/work_actor_spec.rb
- spec/controllers/hyrax/works_controller_spec.rb
- spec/features/create_work_spec.rb
- spec/forms/hyrax/work_form_spec.rb
- spec/models/work_spec.rb
- spec/presenters/hyrax/work_presenter_spec.rb
* Adds default admin set by running task hyrax:default_admin_set:create.
* Adds work type of 'Work'.
> Adds more required set up

- Gemfile
- Gemfile.lock
- spec/factories/user.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/support/factory_bot.rb
* Adds factory_bot gem to the bundle, and makes it available in tests.
* Adds a basic User factory.
> Adds FactoryBot

- app/views/_user_util_links.html.erb
- config/locales/hyrax.en.yml
- spec/views/_user_util_links.html.erb_spec.rb
**NOTE:** this PR is missing an integration test, but I added it as part of the acceptance criteria for fixing bug [AMS2-72](https://jira.weareavp.com/browse/AMS2-72)
> Adds link to change password to menu

- Gemfile
- Gemfile.lock
- app/controllers/admin/users_controller.rb
- app/models/ability.rb
- app/views/_user_util_links.html.erb
- app/views/admin/users/_form.html.erb
- app/views/admin/users/new.html.erb
- config/locales/ams.yml
- config/role_map.yml
- config/routes.rb
- db/seeds.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/factories/user.rb
- spec/features/admin_user_spec.rb
- spec/rails_helper.rb
- spec/support/controller_macros.rb
* Adds form for admins for User creation
* Creates admin user seed
Closes AMS2-54, Closes AMS2-55, Closes AMS2-57, Closes AMS2-3
> Completes new user creation for AMS admins

- .gitignore
- spec/features/user_management/change_password_spec.rb
Also,
* Adds avatar upload location to gitignore.
Closes AMS2-69.
> Adds integration test for changing password

- .travis.yml
- bin/install.sh
- config/role_map.yml
This should fix the current broken build in travis
> adding production deployment config

- config/environments/production.rb
Uses an environment variable to define mailer host for Devise.
> Uses env var for Devise mailer host

- Gemfile
- Gemfile.lock
- app/controllers/concerns/hydra/role_management/roles_behavior.rb
- app/controllers/roles_controller.rb
- app/models/ability.rb
- app/models/user.rb
- app/views/hyrax/dashboard/sidebar/_configuration.html.erb
- app/views/roles/_add_user_modal.html.erb
- app/views/roles/edit.html.erb
- app/views/roles/index.html.erb
- app/views/roles/new.html.erb
- config/locales/hyrax.en.yml
- config/routes.rb
- db/migrate/20180307161802_user_roles.rb
- db/schema.rb
- spec/controllers/admin/users_controller_spec.rb
- spec/factories/user.rb
- spec/models/user_spec.rb
Adding hydra-role-management gem
Adding navigation link to Admin Dashboard sidebar
Adding locale lang for roles
> AMS2-20 roles management

- config/environments/production.rb
- config/initializers/devise.rb
> AMS2-58: Sets up Amazon SES for Production

- appspec.yml
- bin/deploy/create_deployment_details_page.rb
- bin/deploy/install.sh
fixes AMS2-104
fixes deployment html page
> fixing deployment issues

- config/initializers/hyrax.rb
- spec/features/create_asset_spec.rb
- spec/features/create_digital_instantiation_spec.rb
- spec/features/create_essence_track_spec.rb
- spec/features/create_physical_instantiation_spec.rb
- spec/features/create_series_spec.rb
- spec/support/guid.rb
Once merged, We might have to manually clean DB.
> AMS2-14 Setting up GUID

- app/forms/hyrax/asset_form.rb
- app/models/asset.rb
- app/models/solr_document.rb
- app/presenters/hyrax/asset_presenter.rb
- app/services/topics_service.rb
- app/views/hyrax/assets/_attribute_rows.html.erb
- app/views/records/edit_fields/_topics.html.erb
- config/authorities/topics.yml
- spec/features/create_asset_spec.rb
> Adds additional Asset fields

- .gitignore
- app/actors/hyrax/actors/asset_actor.rb
- app/forms/hyrax/asset_form.rb
- app/indexers/asset_indexer.rb
- app/input/multiple_dates_with_types_input.rb
- app/models/asset.rb
- app/models/solr_document.rb
- app/presenters/hyrax/asset_presenter.rb
- app/services/date_types_service.rb
- app/views/hyrax/assets/_attribute_rows.html.erb
- app/views/records/edit_fields/_dates_with_types.html.erb
- config/authorities/date_types.yml
- spec/features/create_asset_spec.rb
- spec/support/asset_form_helpers.rb
This follows the same pattern for title types and description types.
> Add fields for entering all date types

- app/forms/hyrax/asset_form.rb
- app/input/multiple_dates_with_types_input.rb
- app/input/multiple_descriptions_with_types_input.rb
- app/input/multiple_titles_with_types_input.rb
- app/views/records/edit_fields/_dates_with_types.html.erb
- config/authorities/date_types.yml
- config/authorities/title_and_description_types.yml
- spec/features/create_asset_spec.rb
Closes AMS2-316 subtask.
Closes AMS2-240. Again.
> Show only one blank option for typed fields

- app/views/hyrax/dashboard/sidebar/_configuration.html.erb
- config/role_map.yml
Update to Hyrax includes an update to this view to include link to edit
Collection Types.
Also adds wgbh_admin@example.org to admin role.
> Updates 'configuraiton' section of sidebar

- config/environments/production.rb
- config/locales/hyrax.en.yml
- spec/features/user_management/change_password_spec.rb
- spec/views/_user_util_links.html.erb_spec.rb
fixes issues for console in production and add new locale for collections for 2.1.0
> small fixes

- lib/ams.rb
- spec/lib/ams_spec.rb
- spec/rails_helper.rb
This role is used for adding and updating admin data specific to AAPB website functionality.
> Adds user role 'aapb-admin'

- app/actors/hyrax/actors/asset_actor.rb
> Fixes bug where episode number wasn't saved as a title type.

- app/assets/stylesheets/global/search_results.css
- app/controllers/catalog_controller.rb
* Also bumps down h3 facet font on catalog#index to accomodate length
> Adds producing_organization facet to CatalogController

- app/controllers/catalog_controller.rb
- app/indexers/ams/work_indexer.rb
- app/indexers/asset_indexer.rb
- app/indexers/contribution_indexer.rb
- app/indexers/digital_instantiation_indexer.rb
- app/indexers/essence_track_indexer.rb
- app/indexers/physical_instantiation_indexer.rb
- app/models/digital_instantiation.rb
- app/models/physical_instantiation.rb
- spec/indexers/hyrax/asset_indexer_spec.rb
Fixes
1. AMS2-405
1. AMS2-469
1. AMS2-407
1. AMS2-470
1. AMS2-313
1. AMS2-411
1. AMS2-409
1. AMS2-410
1. AMS2-412
Screenshot:
> Blacklight facets

- app/controllers/catalog_controller.rb
Based on feedback from review on demo, we needed to remove some fields from catalog#index.
> Removes unwanted fields from catalog#index

- app/controllers/catalog_controller.rb
- app/views/catalog/search_filters/_date_range_filter.html.erb
> Defaults facets and filters on catalog#index to closed

- app/assets/stylesheets/work_show/work_show.css
- app/presenters/hyrax/digital_instantiation_presenter.rb
- app/presenters/hyrax/essence_track_presenter.rb
- app/presenters/hyrax/physical_instantiation_presenter.rb
- app/views/hyrax/base/show.html.erb
- config/initializers/assets.rb
> AMS2-481 Apply css and layout to all work types

- app/actors/hyrax/actors/asset_actor.rb
- app/forms/hyrax/asset_form.rb
- app/input/ams/multi_typed_input.rb
- app/input/multiple_dates_with_types_input.rb
- app/input/multiple_descriptions_with_types_input.rb
- app/input/multiple_titles_with_types_input.rb
- app/models/asset.rb
- app/models/solr_document.rb
- app/presenters/hyrax/asset_presenter.rb
- app/services/ams/typed_field_service.rb
- app/services/date_types_service.rb
- app/services/description_types_service.rb
- app/services/title_types_service.rb
- app/views/hyrax/assets/_attribute_rows.html.erb
- config/authorities/description_types.yml
- config/authorities/title_types.yml
- spec/features/create_asset_spec.rb
- spec/features/create_asset_with_digitalinstantiation_spec.rb
- spec/support/asset_form_helpers.rb
Fixes
1. AMS2-507
1. AMS2-508
also refactor code for typed fields.
> adding series title and description and refactoring code

- spec/support/date_range_filter_helpers.rb
The facet was defaulting to closed, so added some logic to open it.
> Fixes broken specs for date range

- app/actors/hyrax/actors/enforce_parent_title.rb
- app/forms/hyrax/contribution_form.rb
- app/forms/hyrax/digital_instantiation_form.rb
- app/forms/hyrax/essence_track_form.rb
- app/forms/hyrax/physical_instantiation_form.rb
- app/forms/inherit_parent_title.rb
- app/models/contribution.rb
- app/models/digital_instantiation.rb
- app/models/physical_instantiation.rb
> fixes parent title bug

- app/controllers/catalog_controller.rb
> AMS2-535 Adding advance search fields

- app/views/catalog/_facets.html.erb
- app/views/catalog/_search_sidebar.html.erb
- app/views/catalog/search_filters/_date_range_filter.html.erb
1. Adds date filter to sidebar
1. Adds Clear button to date filter to remove the filter
1. Apply css to expand the filter and make it active css class when filter is applied.
> ASM2-515  & AMS2-516 

- app/controllers/catalog_controller.rb
- app/mailers/application_mailer.rb
- config/environments/development.rb
@adeelahmad should probably review this before @afred merges. When I pulled this branch I had to delete come pbcore export from the CatalogController that didn't seem to be working.
> AMS2-540 - Adds CSV export to ActiveJob

- Gemfile.lock
- app/models/ability.rb
- config/environments/development.rb
- config/routes.rb
- db/migrate/20181115174437_create_hyrax_batch_ingest_batches.hyrax_batch_ingest.rb
- db/migrate/20181115174438_create_hyrax_batch_ingest_batch_items.hyrax_batch_ingest.rb
- db/schema.rb
- spec/features/batch_ingest_spec.rb
Adds the results of running the installer, and adds a feature spec.
> Install hyrax-batch_ingest gem

- Gemfile.lock
- app/assets/stylesheets/application.css
- app/controllers/catalog_controller.rb
- app/views/catalog/_search_form.html.erb
This is the result of merging `master` into `develop`.
Since `develop` is a protected branch, I can't push the merge commit directly to `develop`, so I created this branch from which to make a PR into `develop`. Once that is merged, then the PR that merges `develop` into `master` _shouldn't_ have any conflicts. 🤞
> Fix conflicts between master and develop

- app/controllers/catalog_controller.rb
- app/models/ams/csv_export_extension.rb
- app/models/solr_document.rb
- app/services/ams/export/documents_to_csv.rb
- app/services/ams/export/documents_to_pbcore_xml.rb
- app/services/ams/export/export_service.rb
- app/views/catalog/_export_search_results.html.erb
- spec/factories/asset.rb
- spec/models/ams/csv_export_extension_spec.rb
- spec/models/solr_document_spec.rb
- spec/services/ams/export/documents_to_csv_spec.rb
> Adds CSV export reports for Digital & Physical Instantiations

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/work_show/work_show.css
- app/views/hyrax/assets/_aapb_admindata.html.erb
- app/views/hyrax/assets/_contributions.html.erb
- app/views/hyrax/assets/_metadata.html.erb
- app/views/hyrax/assets/show.html.erb
- spec/features/create_asset_spec.rb
- spec/features/create_asset_with_asset_types_vocabulary_spec.rb
- spec/features/create_asset_with_genre_vocabulary_spec.rb
Updates the design on asset#show. Reviewed with @sroosa.
> 589 Asset Design

- app/assets/stylesheets/global/search_results.css
- app/models/solr_document.rb
- app/views/catalog/_index_list_default.html.erb
- spec/models/solr_document_spec.rb
Updates catalog#index view per the ticket. Failing because it needs the solr_wrapper gem update in this PR: #190.
> 591 search index design

- app/services/wgbh/batch_ingest/pbcore_xml_mapper.rb
- spec/factories/pbcore_xml/instantiation/alternative_modes.rb
- spec/factories/pbcore_xml/instantiation/channel_configuration.rb
- spec/factories/pbcore_xml/instantiation/colors.rb
- spec/factories/pbcore_xml/instantiation/date.rb
- spec/factories/pbcore_xml/instantiation/dimensions.rb
- spec/factories/pbcore_xml/instantiation/duration.rb
- spec/factories/pbcore_xml/instantiation/generations.rb
- spec/factories/pbcore_xml/instantiation/identifier.rb
- spec/factories/pbcore_xml/instantiation/location.rb
- spec/factories/pbcore_xml/instantiation/media_type.rb
- spec/factories/pbcore_xml/instantiation/physical.rb
- spec/factories/pbcore_xml/instantiation/rights.rb
- spec/factories/pbcore_xml/instantiation/standard.rb
- spec/factories/pbcore_xml/instantiation/time_start.rb
- spec/factories/pbcore_xml/instantiation/tracks.rb
- spec/factories/pbcore_xml/pbcore_instantiation_document.rb
- spec/services/wgbh/batch_ingest/pbcore_xml_mapper_spec.rb
> 618 physical instantiation ingest mapping

- app/actors/hyrax/actors/digital_instantiation_actor.rb
- app/assets/stylesheets/global/work_show.css
- app/models/solr_document.rb
- app/presenters/ams/asset_file_presenter.rb
- app/presenters/hyrax/asset_presenter.rb
* Stores frame_height and frame_width in DigitalInstantiationActor
* Adds top level empty range for iiif_av
* Only uses Hyrax::IiifAv::ManifestRange if we have media
> Finalizes player display on asset#show

- app/models/essence_track.rb
Updates the validations on essence_track so that the error messages get added to base for the hyrax form view.
> Updates essence_track validations

- app/assets/stylesheets/global/work_show.css
My original PR for this removed an !important flag from this CSS. Adding it back to hopefully make it work on edge. Works locally without it, though.
> Don't argue with !important

- app/forms/hyrax/digital_instantiation_form.rb
- app/forms/hyrax/essence_track_form.rb
- app/forms/hyrax/physical_instantiation_form.rb
- app/indexers/asset_indexer.rb
- app/indexers/digital_instantiation_indexer.rb
- app/indexers/essence_track_indexer.rb
- app/indexers/physical_instantiation_indexer.rb
- app/services/aapb/asset_thumbnail_path_service.rb
- app/services/aapb/batch_ingest.rb
- app/services/aapb/batch_ingest/batch_item_ingester.rb
- app/services/aapb/batch_ingest/batch_reader.rb
- app/services/aapb/batch_ingest/csv_config_parser.rb
- app/services/aapb/batch_ingest/csv_item_ingestor.rb
- app/services/aapb/batch_ingest/csv_reader.rb
- app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb
- app/services/aapb/batch_ingest/pbcore_xml_mapper.rb
- app/services/aapb/batch_ingest/zipped_pbcore_reader.rb
- app/services/aapb/metadata_service.rb
- app/services/aapb/work_thumbnail_path_service.rb
- app/services/wgbh/batch_ingest.rb
- config/batch_ingest.yml
- spec/features/batch_ingest/aapb_pbcore_zipped_spec.rb
- spec/services/aapb/batch_ingest/pbcore_xml_item_ingester_spec.rb
- spec/services/aapb/batch_ingest/pbcore_xml_mapper_spec.rb
- spec/services/aapb/batch_ingest/zipped_pbcore_reader_spec.rb
> 651 Renames Services from WGBH to AAPB

- bin/deploy/install.sh
- bin/deploy/verify_service.sh
* Sources /etc/profile in verify_deployment.sh so that PRODUCTION_HOST env var is available.
* Prefixes rails commands with 'bundle exec' in install.sh.
> Fixes deploy scripts

- spec/factories/pbcore_xml/instantiation/date.rb
- spec/factories/pbcore_xml/pbcore_title.rb
Needed to generate large datasets using factories.
> Less repeating of demo data

- app/views/hyrax/batch_ingest/batches/new.html.erb
This PR hides the submitter_email field on batch#new and submits the current user's email.
> 613 Batch Submitter

- app/services/rights_link_service.rb
- app/views/records/edit_fields/_rights_link.html.erb
- app/views/records/edit_fields/_topics.html.erb
- config/authorities/rights_link.yml
- spec/features/create_asset_with_digitalinstantiation_spec.rb
Changes rights link to multi-select and adds controlled RightsLink controlled vocab.
> 382 rights link

- app/assets/stylesheets/work_show/work_show.css
- app/views/hyrax/assets/_show_actions.html.erb
- app/views/hyrax/assets/_work_title.erb
Design approved by @sroosa. This also gives more space for Asset titles.
> Formats asset#show action buttons

- app/actors/hyrax/actors/asset_actor.rb
- app/services/aapb/batch_ingest/pbcore_xml_mapper.rb
- config/initializers/batch_ingest_requires.rb
1) Map admin data to correct field names in pbcore_xml_mapper
2) Don't include admindata in annotations field
> 676 map admin data

- app/services/aapb/batch_ingest/csv_item_ingestor.rb
- app/services/aapb/batch_ingest/csv_reader.rb
1. Fixes Multi Value Attributes in CSV Ingester
> Fixes Multi Value Attributes in CSV Ingester

- app/controllers/hyrax/my_controller.rb
Filtering by batch_id just needed the addition of the hyrax_batch_ingest_batch_id to the dashboard controller configure_facets method.
> Overwrites dashboard my_controller.rb to add Batch ID filter

- app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb
When using multi-threaded concurrence (Sidekiq) and RDBMS (MySQL) we were
had a situation where Sipity::Agent for a given user had been created in
one thread, but was not accessible from another thread. In this situation
the necessary Sipity::Agent could niether be retrieved, nor created,
resulting in a nil value that would then result in the validation error.
Here we just synchronously create the Sipity::Agent before scheduling jobs.
> Fix 'Agent must exist' validation error

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
Apparently Travis was having issues getting an incompatible chromedriver for Selenium.
This hopefully fixes that.
> Adds webdrivers gem

- config/ci.yml
> Adds quotes around Sony Ci credential env variables

- app/services/aapb/batch_ingest/pbcore_xml_mapper.rb
my fix for instantiation duration broke cases where duration is not there.
> Fixes undefined method gsub

- app/controllers/catalog_controller.rb
- app/helpers/application_helper.rb
> Fix Search Results Thumbnail

- .rspec
- .travis.yml
- Gemfile.lock
- LICENSE
- spec/rails_helper.rb
> Add Hyrax's full text license

- app/services/aapb/batch_ingest/zipped_pbcore_digital_instantiation_reader.rb
- app/services/aapb/batch_ingest/zipped_pbcore_reader.rb
- config/environments/development.rb
- config/locales/hyrax.en.yml
- spec/fixtures/batch_ingest/sample_pbcore_digital_instantiation_2/digital_instantiation_manifest.csv
- spec/fixtures/batch_ingest/sample_pbcore_digital_instantiation_2/sample_digital_instantiation.xml
- spec/services/aapb/batch_ingest/zipped_pbcore_digital_instantiation_reader_spec.rb
Processes CSVs, better error message for invalid manifest, & tests.
> 385 Digital Instantiation Ingest

- app/services/aapb/batch_ingest/csv_item_ingester.rb
Refactors CSVItemIngester#clean_failed_batch_item_work a bit..
1) renames method to not get confused with actual BatchItem model.
2) needs ony 1 param instead of 2
3) Rescues from StandardError (the default) rather than Exception, as per Ruby
best practices.
> Small refactor

- app/services/aapb/batch_ingest/csv_item_ingester.rb
> check if failed child object is from same batch as parent asset

- app/services/aapb/batch_ingest/csv_item_ingester.rb
I accidentally lost a crucial bit of logic during a recent rebase.
> Fix an oopsie.

- Gemfile
- Gemfile.lock
- app/models/asset.rb
- app/services/ams/asset_destroyer.rb
- bin/scripts/destroy_assets
- spec/services/ams/asset_destroyer_spec.rb
- spec/support/custom_rspec_matchers.rb
Usage:
./bin/scripts/destroy_assets asset_ids.txt
Where "asset_ids.txt" is a file containing Asset IDs to destroy, one per line.
You must pass in the Rails enviornment if you want to use it in production, e.g.
RAILS_ENV=production ./bin/scripts/destroy_assets asset_ids.txt
Closes #413.
> Adds bulk delete for Assets via command line

- app/forms/hyrax/asset_form.rb
- app/indexers/asset_indexer.rb
- app/models/ams/pbcore_xml_export_extension.rb
- app/models/solr_document.rb
- app/presenters/aapb/attribute_indexed_to_parent_presenter.rb
- app/presenters/aapb/instantiation_admin_data_presenter.rb
- app/presenters/hyrax/asset_presenter.rb
- app/presenters/hyrax/digital_instantiation_presenter.rb
- app/presenters/hyrax/physical_instantiation_presenter.rb
- app/renderers/hyrax/renderers/indexed_to_parent_renderer.rb
- app/services/aapb/batch_ingest/pbcore_xml_mapper.rb
- app/views/hyrax/assets/_aapb_admindata.html.erb
- app/views/records/edit_fields/_organization.html.erb
- db/migrate/20200513190614_add_organization_to_aapb_admin_data.rb
- db/schema.rb
- db/schema.test.rb
- spec/presenters/aapb/attribute_indexed_to_parent_presenter_spec.rb
- spec/renderers/hyrax/renderers/indexed_to_parent_renderer_spec.rb
Due to the indexing strategy for instantiations that are indexed to parents, in order to get this to work we had to create a new renderer for :symbols since Hyrax doesn't have one. Also uses parent doc for link to catalog#index.
> 434 Holding Org

- app/services/ams/export/export_service.rb
> Fixes NoMethodError in export records notification

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
- spec/presenters/hyrax/asset_presenter_spec.rb
> Fixes time of day display for last_pushed

- bin/deploy/install.sh
Changes command to restart HTTPD.
> Updates install.sh for Amazon Linux 2

- .travis.yml
* Changes branch condition to match 'develop' for deployment to Demo stack.
* Adds deploy config to deploy to Prod stack when branch is 'main'.
> Fixes deploy config, again

- config/batch_ingest.yml
> Allows updating of an Assets organization annotation

- config/authorities/topics.yml
Corrects spelling of Asset topic "Performing Arts." Closes #602
> Updates Performing Arts spelling
