Rakefile
lib/tasks/hydra_clean_server.rake

Resets database, clears out Fedora and Solr, and creates the default admin set.

Adds rake task for resetting a clean dev env

---

app/actors/hyrax/actors/asset_actor.rb
app/forms/hyrax/asset_form.rb
app/input/multiple_text_select_combo_input.rb
app/models/asset.rb
app/models/solr_document.rb
app/presenters/hyrax/asset_presenter.rb
app/services/title_and_description_types_service.rb
app/views/hyrax/assets/_attribute_rows.html.erb
app/views/records/edit_fields/_titles_with_types.html.erb
config/authorities/asset_types.yml
config/authorities/title_and_description_types.yml
spec/features/create_asset_spec.rb
spec/features/create_asset_with_asset_types_vocabulary_spec.rb
spec/features/create_asset_with_digitalinstantiation_spec.rb
spec/features/create_asset_with_genre_vocabulary_spec.rb
spec/support/asset_form_helpers.rb

* Adds distinct properties for various title types to the Asset model.
* Creates a custom input that combines a text inputs with a selet box for the
type.
* Modifies AssetForm object to split distinct properties for each title type
into a structure suitable for displaying as a combination of select box (for
the title type) and a text box (for the title).
* Adds logic to AssetActor to modify the environment on #create and #update. The
modifications combine the title and title type fields from the submitted
form data into distinct properties for each title type on the model before
saving.
* Modifies form partials for edit fields to allow for multiple title/title_type
paris, and ensure they are pre-populated.
* Modifies AssetPresenter, relevant view partials to display all the different …

Adds typed title field

---

app/views/hyrax/digital_instantiations/_form_metadata.html.erb
lib/tasks/hydra_clean_server.rake

This involves overriding app/views/base/_form_metadata.html.erb partial, which
in turn overrides the partial of the same name from Hyrax gem.
Here, we need extra customization for Digitial Instantiations, so
we override the partial by addifng a new partial for
app/views/digital_instantiations/_form_metadata.html.erb
Also...
* Adds seeding of database to hydra:clean:server and hydra:clean:test_server
rake tasks to ensure that running either task will result in a clean state
of the persistence layer.

Adds msg re: uploading technical metadata

---

config/initializers/locale.rb

This will require that the default CollectionType rake task will need to be re-run on edge and staging instances.
`rails hyrax:default_collection_types:create`

Adds initializer for locale files

---

Gemfile
Gemfile.lock

Apache stopped publishing the version of Solr that the previous
version of solr_wrapper was trying to pull down. Upgrading to
~> 2.0 fixes this.

Updates solr_wrapper

---

app/models/solr_document.rb
spec/models/asset_spec.rb
spec/models/solr_document_spec.rb

Works having multiple title types should concatenate them together if present.
Also, modifies spec for Asset model:
* use convention of using 'describe' for describing method calls
* use convention of using '#' to denote instance methods.
* use single `let` statement for top-level describe block  instead of one
for each context in the spec.

Adds concatenated titles

---

Gemfile
Gemfile.lock
app/models/search_builder.rb
spec/features/create_asset_with_digitalinstantiation_spec.rb

* Modifies SearchBuilder#models to only return Asset model.
* Temporarily tells Gemfile to fetch Hyrax from WGBH-MLA/hyrax fork in Github.
Once the patch to Hyrax is backported to 2.x and published, we can fetch Hyrax
from rubygems.org again.
Also,
* Fixes Create Asset with Digital Instantiation spec.

Only return Asset work types in search results.

---

app/models/asset.rb
app/models/digital_instantiation.rb
app/models/essence_track.rb
app/models/physical_instantiation.rb
app/services/ams/time_code_service.rb
app/views/records/edit_fields/_dimensions.html.erb
app/views/records/edit_fields/_duration.html.erb
app/views/records/edit_fields/_time_start.html.erb
spec/models/asset_spec.rb
spec/services/ams/duration_service_spec.rb
spec/support/have_propety_matcher.rb

* Changes predicate for PBS Nola Code to EBUCore hasIdentifier.
* Changes input validation for Duration fields.
* Changes input type for Dimensions fields.
* Adds a DurationService to ensure consistency with validation by regex.
Also,
* Adds a custom matcher for checking properties and predicates of ActiveFedora models.
* Refactors Asset model test to use new factor (cuts back on a lot of loc).
Closes AMS2-393.

Updates Asset model

---

app/assets/stylesheets/global/search_results.css
app/controllers/catalog_controller.rb
app/models/ams/csv_export_extension.rb
app/models/solr_document.rb
app/search_builders/ams/search_builder.rb
app/views/catalog/_export_search_results.html.erb
app/views/catalog/_search_form.html.erb
app/views/catalog/export.csv.erb
config/routes.rb

1. Adds download dropdown widget to blacklight `catalog` controller , partial redirect user to download action
2. Adds `catalog_export` route
3. Adds `export` method to `catalog` controller
4. Fixes advance search by adding `:add_advanced_search_to_solr` to `AMS::SearchBuilder`
5. Fixes css for search bar

AMS2-489 adds csv export and minor fixes

---

config/authorities/asset_types.yml
config/authorities/format.yml

Some edit.s to controlled vocabularies, including avoiding quotation marks and adding spaces to ids, where we missed that before

Add space to Asset Type id 

---

app/views/hyrax/dashboard/sidebar/_repository_content.html.erb

This overwritten Hyrax template gets generated into the host app from the hyrax-batch_ingest
gem. However, there is no rake task to copy the template after the gem has already been
installed, so here we do it manually.

Adds 'Batches' link to dashboard

---

spec/factories/pbcore_xml/instantiation/date.rb
spec/factories/pbcore_xml/pbcore_description.rb
spec/factories/pbcore_xml/pbcore_title.rb
spec/services/aapb/batch_ingest/zipped_pbcore_reader_spec.rb

I think this should keep the data unique to fix the intermittent errors from the xpath spec helper.

663 Unique PBCore Factory Data

---

app/actors/hyrax/actors/digital_instantiation_actor.rb
app/models/essence_track.rb
app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb
app/services/aapb/batch_ingest/pbcore_xml_mapper.rb
spec/factories/pbcore_xml/instantiation/essence_track/time_start.rb
spec/models/essence_track_spec.rb
spec/services/aapb/batch_ingest/pbcore_xml_item_ingester_spec.rb
spec/services/aapb/batch_ingest/pbcore_xml_mapper_spec.rb

Modifies PBCoreXMLItemIngester to save EssenceTrack records for
PhysicalInstantiations and DigitalInstantiations.
NOTE: EssenceTrack PBCore metadata for DigitalInstantiations is mapped within
the DigitalInstantiationActor, but for Physical Instantiations, it's mapped
using the PBCoreXMLMapper within the PBCoreXMLItemIngester, and each
Essence Tracks is added one at a time to it's parent.
Also,
* Includes slight refactor of PBCoreXMLItemIngester.
* Fixes cardinality issue with aspect ratio in Essence Track records; was
multiple, should be single-valued.
* Fixes mapping of PBCore xml annotations; was mapping to 'annotations'
but should map to 'annotation'
* Fixes bug in factories re: date formats; was generating hh::mm::ss:xyz but
should be hh::mm::ss.xyz (seconds use decimal for fractions, …

Saves EssenceTracks in batch PBCore XML ingest

---

app/views/hyrax/assets/show.html.erb

This ensures that turbolinks loads the video player.

Adds turbolinks tag to head for asset#show

---

lib/ams.rb
spec/features/admin/admin_sets/add_userrole_as_viewer_spec.rb

In production environments, the Redis server is set in an env var. Use that first
and default to localhost if it's not there.

Uses REDIS_SERVER for redis host

---

Gemfile
bin/deploy/install.sh

This is generally a good idea, but necessary because Spring was running in
prodution and causing a weird multi-inclusion error.
Also adds database_cleaner to the production bundle so we can use the
ams:reset_data rake task in production environments, i.e. on Edge server.

Installs gems without deployment or test groups

---

config/environments/production.rb

This is to avoid an issue of the hyrax-batch_ingest gem calling const_get from within
a job that is being executed in parallel; for some reason, it hangs indefinitely in
a Sidekiq 'busy' state.

Sets eager_load to true for Production env

---

db/migrate/20190307145823_change_source_data_to_text.hyrax_batch_ingest.rb
db/schema.rb

New migration changes hyrax_batch_ingest_batch_items.source_data field from
varchar to text because it needs to be able to hold more data.

Adds new migration from batch ingest gem

---

app/models/ams/identifier_service.rb
app/models/asset.rb
app/models/contribution.rb
app/models/digital_instantiation.rb
app/models/essence_track.rb
app/models/physical_instantiation.rb
config/initializers/hyrax.rb
lib/ams.rb
spec/support/guid.rb

We were running into issues in deployed environments with our stateful minter,
which requires providing concurrent access to a single persistence layer where
the minter state is stored. Our IDs are random, and we don't have a use case for
"replaying" the minting of them, so we can switch to a stateless minter and
avoid the persistence layer requirement, and associated headaches.
Our stateless minter replaces NOID, and is just the first 12 chars of a UUID
with the constant prefix "cpb-aacip-" prepended to it.
For every ID minted, we do a lookup in Solr to see if the ID exists yet, and if
it does, we regenerate a new random ID.
Also...
* Provides an accessor to AMS.seeds, for manually creating seed data. This has
proen useful more than once in development, so added it in.

Use stateless ID minter for new AAPB ID

---

app/assets/javascripts/global/datepicker.js
app/services/aapb/batch_ingest/pbcore_xml_mapper.rb
app/views/hyrax/assets/_aapb_admindata.html.erb

Fixes bracket issue for admindata fields.
Admin data handling in `pbcore_xml_mapper` did not account for single- versus multi-value fields. Now, it do.

Fix Bracket Issue For Admin Data Fields

---

app/jobs/cool_physical_job.rb
app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb
spec/features/batch_ingest/aapb_pbcore_zipped_spec.rb
spec/support/deposit_helpers.rb

For 'AAPB PBCore Zipped' ingests, BatchItems created after the initial reading
of the batch were not receiving any value for 'ID within batch', which is the
filename within the zipped batch. This ensures those additonal batch items
have the right filename in that field.
Also,
* Small refactor of test for AAPB PBCore Zipped ingest a bit for readability.

All BatchItems have correct 'ID within batch'

---

app/actors/hyrax/actors/asset_actor.rb
app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb
app/services/aapb/batch_ingest/zipped_pbcore_digital_instantiation_mapper.rb
db/schema.test.rb
spec/features/batch_ingest/aapb_pbcore_zipped_spec.rb
spec/services/aapb/batch_ingest/pbcore_xml_item_ingester_spec.rb

#292
Adds method (`check_for_errors`) for each AMS model to surface validation errors and raise an exception.

Check for errors

---

app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb

this is just leftover cruft from an implementation that never happened.

Remove rescue clause that doesn't work

---

app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb
app/services/aapb/batch_ingest/pbcore_xml_mapper.rb

* Ensures that tranlated AAPB IDs will be prefixed with cpb-aacip- rather than
cpb-aacip_ (i.e dash rather than underscore) which is consistent with newly
generated AAPB-style IDs.
* Cleans out errant trailing question mark in duration values; relic from AMS1.
* Outputs object and field names when raising validation errors.

Fixes some ingest formatting and error reporting

---

solr/config/schema.xml
solr/config/solrconfig.xml

Remove all 'suggest' features. The 'suggest' thing slows things way down, and we
think it's also causing stack overflows.
NOTE: the Solr config and schema are not used directly from this repo, but
are intended to be copied to, and used in, the Solr instance used by AMS.

Updates Solr config and schema

---

app/models/asset.rb
app/models/digital_instantiation.rb
app/models/physical_instantiation.rb
spec/factories/asset.rb
spec/factories/contribution.rb
spec/factories/digital_instantiation.rb
spec/models/asset_spec.rb
spec/models/digital_instantiation_spec.rb
spec/models/physical_instantiation_spec.rb

The after_destroy hook is used for ActiveFedora models to destroy child object
after parent is destroyed. This effectively is a 'cascade' delete.
* Asset#destroy deletes PhysicalInstantiations, DigitalInstantiations,
Contributions, and AdminData
* PhysicalInstantiation#destroy and DigitalInstantiation#destroy deletes
Contributions and EssenceTracks
Also, updates factories to use ordered_members to be consistent with how models
are associated in the app.

Destroys child Works when Parent is deleted

---

app/helpers/application_helper.rb
app/models/ams/cascade_destroy_members.rb
app/models/asset.rb
app/models/digital_instantiation.rb
app/models/physical_instantiation.rb
lib/ams/aapb_pbcore_zipped_batch_ingest_fixer.rb
spec/lib/ams/aapb_pbcore_zipped_batch_ingest_fixer_spec.rb
spec/models/asset_spec.rb

The previous attempt didn't work for models created with actors because deleting
the Asset made it impossible to access the Asset#ordered_members (although for
reasons unknown, this wasn't a problem in the Asset model spec).
This change deletes objects from Asset#members rather than Asset#ordered_members
which seems to work.
The point of adding cascade delete, was so that we can identify Assets that were
ingested via the 'AAPB PBCore XML Zipped' batch ingest, but which had child
objects that failed ingest. In this case, we want to delete the Asset and all
it's ingested children, so that we can re-ingest it with the same IDs.
This PR also adds a utility, AMS::AAPBPBCoreZippedBatchIngestFixer, which does
just that, when given a batch id.

Fix bug with cascade delete

---

app/models/ams/cascade_destroy_members.rb

The 'cascade delete' is an after_destory hook that calls #destroy! on an ActiveFedora
record's #members. If one of those members had already been deleted for some reason,
an LDP::Gone error was getting raised. We want to quietly rescue from that instead.

Don't raise error on cascade delete

---

app/services/aapb/batch_ingest/errors.rb
app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb
spec/helpers/application_helper_spec.rb
spec/services/aapb/batch_ingest/pbcore_xml_item_ingester_spec.rb

If the Asset being ingested is already in Fedora, then it will raise an
exception that will be caught in the BatchItemProcessingJob's rescue_from block,
where the error msg it saved on the BatchItem instance.
Also,
* Creates a custom error class for AAPB::BatchIngest::RecordExists.
* Adds a spec for ApplicationHelper#display_date, which failed to get added a
while ago for reasons unknown.
Closes #333.

Checks to see if Asset exists before ingesting

---

bin/deploy/install.sh
bin/scripts/ensure_sidekiq_running.rb
lib/ams/sidekiq_process_manager.rb

Also, uses bundle exec when calling bin/scripts/ensure_sidekiq_running.rb to within install.sh to fix error of not being able to load sidekiq/api.

Appends to, rather than truncates, sidekiq log.

---

.rspec
.travis.yml
Gemfile.lock
spec/rails_helper.rb

We were getting errors that the version of ChromeDriver was incompatible with
the version of Chrome that Travis was running.
After much debugging, we found that a recently released version of Chrome was
not compatible with the 'trusty' Linux distribution that our Travis CI config
was specifying.
We upgraded our Linux distribution from `trusty` to `xenial`, but in so doing,
our Travis configuration for JDK `oraclejdk8` became incompatible.
Upgrading the distribution from `trusty` to `xenial` then caused an issue with
running `oraclejdk8` (required by Fedora and Solr), because `xenial` is
incompatible with `oraclejdk8`.
We changed our JDK config to use `openjdk11` and changed how we start xvfb, from
calling an init.d script, to using Travis config `services` option. This seems
to have …

Fixes broken Travis builds

---

bin/deploy/install.sh
config/initializers/deployment_info_page_generator.rb
lib/ams/sidekiq_process_manager.rb
lib/tasks/verify_service.rake

There is some issue with the deployment IAM role not having access to one
of the CodeDeploy api methods. I hope to figure that out soon, but in the
meantime, I don't want the deployment info page failure to fail the whole
deployment. Instead log the message to STDERR, replace the deployment info page
with a readable error, and continue without failing.

Graceful failure for deployment info page

---

bin/deploy/install.sh

Sidekiq was not properly restarting after deployment because I was using the
wrong env var.

Fixes sidekiq restart

---

app/services/aapb/batch_ingest/pbcore_xml_mapper.rb
spec/factories/pbcore_xml/instantiation.rb
spec/factories/pbcore_xml/pbcore_description_document.rb
spec/features/batch_ingest/aapb_pbcore_zipped_spec.rb
spec/services/aapb/batch_ingest/pbcore_xml_item_ingester_spec.rb
spec/services/aapb/batch_ingest/pbcore_xml_mapper_spec.rb
spec/support/pbcore_xpath_helpers.rb

Fields for AdminData db records, which are associated with Asset records in
Fedora, are taken from a series of typed <pbcoreAnnotation> elements. We did
not have a test in place to ensure this mapping, nor for ensuring the accurate
creation of the AdminData record, and we encountered bugs that showed the
AdminData was not getting populated correctly in production. This PR adds those
specs.
* Adds a spec for ensuring the propper mapping from PBCore XML to the interim
Hash that is then sent along to the actor stack.
* Adds an integration spec for ensuring that a non-empty AdminData record gets
created as part of the ingest of an Asset.
* Modifies pbcore_description_document factory to add typed annotation for admin
data
* Adds factory params to pbcore_identifer for adding annotations for:
* …

Adds tests for mapping, ingestion of admin data

---

Gemfile
Gemfile.lock
app/views/roles/_add_user_modal.html.erb
app/views/roles/index.html.erb
app/views/roles/new.html.erb
config/locales/hyrax.en.yml

In looking at the history, I'm not sure why we were using our own translations for the Role Manager views. I reverted to using the gem's translations where applicable and pinning our gem version.

Updates Role Views to Use Role Manager Translations

---

app/models/ability.rb
app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb
spec/features/admin/admin_sets/add_multiple_userrole_as_manager_spec.rb
spec/features/admin/admin_sets/add_multiple_userrole_as_viewer_spec.rb
spec/features/admin_add_userrole_as_adminset_manager_spec.rb
spec/features/create_asset_spec.rb
spec/features/create_asset_with_asset_types_vocabulary_spec.rb
spec/features/create_asset_with_digitalinstantiation_spec.rb
spec/features/create_asset_with_genre_vocabulary_spec.rb
spec/features/redirect_new_action_spec.rb
spec/models/ability_spec.rb
spec/services/aapb/batch_ingest/pbcore_xml_item_ingester_spec.rb
spec/support/deposit_helpers.rb

Hyrax's authorization system has a few moving parts.
1. The applications's `Ability` class, which includes `CanCan::Ability`.
2. `Hyrax::Ability` and `Hydra::Ability` mixings that are injected into the
app's `Ability` class.
3. Application data stored in DB tables that inform permissions defined in
the `Hyrax::Ability` and `Hydra::Ability` mixins.
Previously our permissions defaulted to be overly permissive, and we wanted
to switch that to be restrictive by default, and selectively permissive based
on group.
Also, some of our custom permissions in the app's `Ability` class were being
overwritten by logic within the `hyrax` and `hydra-access-controls` gem.
As a result, some of our tests were passing based on false positives due to the
overly permissive rules, or to rules we had specified …

Refactors permission configuration

---

app/jobs/export_records_job.rb

The Blacklight config required to prevent capping exports at 100 got erroneously
removed from the previous PR that was intended to fix it. My fault. This puts it
back in there.

Fixes export cap of 100 results

---

app/presenters/ams/asset_file_presenter.rb

This was so apparent once I recreated locally. "Audio" was not matching "audio" and no display content was getting passed to iiif_manifest.

Downcase the Upcase

---

app/controllers/pushes_controller.rb
app/helpers/application_helper.rb
app/jobs/export_records_job.rb
app/services/ams/export/export_service.rb
app/views/catalog/_export_search_results.html.erb
lib/ams/aapb.rb

-Split push queries into 100-record batches so solr uri doesnt get too long and cause 414 error
-Move push query functions into ApplicationHelper
-Eliminate superfluous `transfer_query` route to avoid too-big query string on redirect
-Other refactoring

Fix rows and split query

---

app/jobs/export_records_job.rb
config/sidekiq.yml

use mailers queue for export records jobs so that jobs run at some point before the heat death of the universe when an ingest is running

Use mailers' queue for export records jobs so that jobs run sooner

---

app/forms/hyrax/asset_form.rb
app/indexers/asset_indexer.rb
app/models/ams/pbcore_xml_export_extension.rb
app/models/solr_document.rb
app/presenters/hyrax/asset_presenter.rb
app/services/aapb/batch_ingest/pbcore_xml_mapper.rb
app/views/hyrax/assets/_aapb_admindata.html.erb
app/views/records/edit_fields/_organization.html.erb
db/migrate/20200513190614_add_organization_to_aapb_admin_data.rb
db/schema.rb
db/schema.test.rb

This PR adds the ability to add a Organization to the AAPBAdminData that is used to populate a PBCore Annotation on the Asset level that is used for ingesting transcripts in to Fix It +.

Adds Organization to AAPBAdminData

---

app/actors/hyrax/actors/asset_actor.rb
app/models/admin_data.rb
db/schema.rb
db/schema.test.rb
spec/models/admin_data_spec.rb

* Adds AdminData#solr_doc to lazily fetch associated Solr doc, if present, using
the AdminData#gid value.
* Adds AdminData#asset to lazily fetch Asset instance, if present, using the
Solr document's ID. If the Asset.find operation raises an error, it's
rescued from, and assigned to AdminData#asset_error.
Also, incidentally updates DB schemas due to running migrations with MySQL.

Adds #solr_doc and #asset methods to AdminData

---

app/controllers/catalog_controller.rb
app/models/ability.rb
app/models/ams/csv_export_extension.rb
app/models/solr_document.rb
app/presenters/hyrax/asset_presenter.rb
app/services/aapb/batch_ingest/pbcore_xml_item_ingester.rb
app/services/level_of_user_access_service.rb
app/services/minimally_cataloged_service.rb
app/services/transcript_status_service.rb
app/views/records/edit_fields/_level_of_user_access.html.erb
app/views/records/edit_fields/_licensing_info.html.erb
app/views/records/edit_fields/_minimally_cataloged.html.erb
app/views/records/edit_fields/_organization.html.erb
app/views/records/edit_fields/_playlist_order.html.erb
app/views/records/edit_fields/_transcript_status.html.erb
config/authorities/level_of_user_access.yml
config/authorities/minimally_cataloged.yml
config/authorities/transcript_status.yml
spec/factories/pbcore_xml/pbcore_description_document.rb
spec/models/ability_spec.rb
spec/presenters/hyrax/asset_presenter_spec.rb

producing_organization suffix got changed with the annotations update because it had it's solr suffix mistakenly updated. This rolls back that update, deletes unused edit_field partials and authorities, and updates the minimally_cataloged facet to use cataloging_status as that's the actual name of the annotation.

Fixes producing_organization solr_document accessor + Cleanup

---

config/environments/production.rb

Debug logging is extremely noisy, and I need to track down ingestion errors, so
switching to Warning level for now (shows warnings and errors).

Change prod log level from :debug to :warn

---

app/helpers/application_helper.rb
app/presenters/hyrax/asset_presenter.rb
spec/helpers/application_helper_spec.rb
spec/presenters/hyrax/asset_presenter_spec.rb

* Changes #last_pushed and #last_updated methods of AssetPresenter to use
ApplicationHelper.dispay_date.
* Modifies ApplicationHelper.display_date to:
* allow input of a different timezone, default to US/Eastern.
* allow input integer timestamp.
* logs date formatting errors to Rails log as a WARN before returning nil.
* Change the date formats of #last_pushed and #last_updated to include the
timezone.
Also,
* refactors specs for AssetPresenter that test for delegated methods; instead of
calling FactoryBot.create(:asset) 45 times, just leave the Asset out of it and
use instance_double(SolrDocument) for the one and only dependency into
AssetPresenter.
Fixes #469.

Fixes date formatting for 'Last pushed to AAPB'

---

app/services/ams/export/documents_to_csv.rb
spec/services/ams/export/documents_to_csv_spec.rb

Closes #470. The tmp file created in the DocumentsToCsv process_export method wasn't opened for writing. Adds w+ to the open and adds back an explicit test on the #process_export method because I think this would have caught it.

Adds w+ to File.open in DocumentsToCsv#process_export

---

app/services/aapb/batch_ingest/csv_item_ingester.rb
spec/services/aapb/batch_ingest/csv_item_ingester_spec.rb

Pulls some of the code used for ingest out of the ingest_object_at method and creates reusable methods for them. This should hopefully make the ingest_object_at a little easier to follow and target issues in specific methods.

Refactors CSVItemIngester to shorten ingest_object_at method

---

app/views/hyrax/assets/_representative_media.html.erb

There was a typo introduced to representative_media partial with the media player update. Should check for "Sound" not "Audio" from DigitalInstantiation.

Looking for Sound in Media Player

---

config/initializers/deployment_info_page_generator.rb

The problem was that the script trying to fetch deployment info was using AWS credentials
for the user who has permissions on S3, but not CodeDeploy.
This uses a different set of credentials which it expects to be correctly set in the
environment. If the expected env vars are empty, the error message will say say.

Fixes deployment info page

---

app/controllers/catalog_controller.rb
app/controllers/hyrax/assets_controller.rb
app/controllers/hyrax/contributions_controller.rb
app/models/solr_document.rb
spec/features/pbcore_xml_endpoints_spec.rb

When on an Asset page, add .xml to the GUID and get the PBCore XML back.
Also,
* Removes redundant inclusion of Hydra::Controller::ControllerBehavior in CatalogController

Adds PBCore XML endpoint

---

.travis.yml
app/controllers/catalog_controller.rb
app/controllers/hyrax/assets_controller.rb
app/controllers/hyrax/contributions_controller.rb
app/models/solr_document.rb
config/initializers/deployment_info_page_generator.rb
spec/features/pbcore_xml_endpoints_spec.rb

First attempt at a continuous deployment merge since:
1. introducing the `main` branch (which will replace `master` after this works)
2. fixing the Travis config for using AWS CodeDeploy to trigger deployments after successful builds.

Merge to Main - Production deployment

---

app/models/annotation.rb

Ensures that a nil annotation type does not raise a NoMethodError #downcase for nil:Class
allowing the more informative error message to be used instead, which is thrown in pbcore_xm_mapper.rb.
NOTE: refactoring validation might make this moot, but for now, it's ok.
Closes #561

Better error message for invalid annotation type

---

app/models/concerns/ams2_pbcore.rb
app/models/concerns/ams2_pbcore_validator.rb
app/services/ams/cleaner/pbcore_cleaner.rb
app/services/ams/cleaner/pbcore_element_editor.rb
app/services/ams/cleaner/pipeline.rb
app/services/ams/cleaner/steps.rb
app/services/ams/cleaner/vocab_map.rb
config/pbcore_cleaner_config.yml
spec/models/concerns/ams2_pbcore_validator_spec.rb
spec/services/ams/cleaner/pbcore_cleaner_spec.rb
spec/services/ams/cleaner/pbcore_element_editor_spec.rb
spec/services/ams/cleaner/steps_spec.rb
spec/services/ams/cleaner/vocab_map_spec.rb

This PR includes a custom validation class for a PBCore Description Document (from the WGBH pbcore gem) that checks for certain types, values, and elements that (while they may be technically valid in PBCore) are not exactly what we want for OUR PBCore. The PR also includes a Cleaner that checks the PBCore for similar characteristics and edits the PBCore Description Document.

Completes Validate and Clean for PBCore

---

spec/models/solr_document_spec.rb

Tests to see that SolrDocument#members brings back more than 10 children.
This is in response to a bugfix where only 10 were being brought back.

Adds spec for SolrDocument#members

---

config/initializers/hyrax.rb

The number of children was being cut off at 10 by default.
Closes #575.

Displays all children of Asset in #show view

---

app/services/aapb/batch_ingest/csv_reader.rb
spec/factories/csv.rb
spec/services/aapb/batch_ingest/csv_reader_spec.rb
spec/support/csv_builder.rb

* Fixes CsvReader to filter out empty values when mapping to BatchItem#source_data JSON.
* Adds a CSV factory following this example: https://id-in-it.com/factorybot-for-csv-file-fixtures
* CsvBuilder is a thin wrapper around CSV ruby lib that simplifies the interface and adds a
#save method that FactoryBot needs for `create`
Fixes #579.

Do not add empty Contributions

---

Gemfile
Gemfile.lock

The error "Only referenceable nodes may be the value of reference properties" is a somewhat cryptic way to say that you're trying to save a new object with an ID that has a tombstone associated with it (i.e. it existed before in the repository, but has since been deleted, but not fully eradicated).
Eradicating the tombstone for these IDs allows us to move forward with the ingest. So that's good, but once again, I found myself really wanting a pry session on our demo machine, so I'm just adding it to the production environment here, for that reason. Debugging in prod env is not ideal, but sometimes you gotta do it to flush out issues specific to the prod environment, and I've had to do that several times now.
closes #586

Adds pry to all environments

---

app/controllers/hyrax/assets_controller.rb
app/services/ams/media_download/media_download_service.rb
spec/services/ams/media_download/media_download_service_spec.rb

The "Download Media" button on the asset#show page in AMS is broken. This PR fixes and refactors the download service class. The refactor here catches download errors and introduces success and failure POROs so that the asset#show page will still display after a failed download and adds the download error to the flash message.
Closes #589.

Refactors MediaDownloadService

---

app/controllers/media_controller.rb
spec/controllers/media_controller_spec.rb

Some error cases were not being covered:
* when SonyCiApi gem returns a SonyCiApi error.
* when the SolrDocument is missing the sonyci_id_ssim field.
* when the sonyci_id_ssim field is there, but empty.
Some of these errors were resulting in ugly 500 errors with HTML rendering. But this controller
is specific to redirect to a Sony Ci URL where the media is, and return the byte stream of the
media, so HTML reponses are out.
Here we always return the redirect on success, and a head response (no body) with the appropriate
HTTP status on failure.
closes #609.

Refactors error handling in MediaController#show

---

app/assets/javascripts/sony_ci/find_media.coffee

This button (as a <a> tag currently) is rendered on the Asset Edit interface in the Admin Data
section of the form, and finds Sony Ci media whose filename matches an Asset's GUID. But it
wasn't working on initial page. The behavior was being added in the turbolinks:load event,
which should work (we're doing it elsewhere), but on this page it simply would not. So I
changed it to use the jQuery(document).ready() method, which typically does NOT work because
of turbolinks, but in this case, it works better. But still not sure why.
Closes #608.

Fix 'Find media in Sony Ci...' button

---

config/authorities/format.yml

Fixes misspelling of "Cartrivision" and the term for "28mm film."
Closes #519

Fixes Cartrivision + 28mm

---

app/controllers/sony_ci/webhooks_controller.rb

Re-indexes Asset after webhook from Sony Ci
The Asset was not being reindexed, and so it was saving on the Asset's admin data, but not the Solr doc.
This explicitly calls Asset#save! to re-index, but Asset#save! also persists in Fedora, which is slow, so if
there's a faster way to just save AdminData and re-index without Fedora, we should do that
Closes #620.

Re-indexes Asset after webhook from Sony Ci
